### ISSUE TITLE
TypeError Laradocs\Moguding\Utils\Json::decode(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by basket-ball** [laradocs/moguding-solution#17]
![image](https://user-images.githubusercontent.com/53385583/202856997-6f441b6c-0966-4adf-966d-537b1a4f0963.png)
环境php8.1，签到没问题但通过server酱通信就报错

**Comment by basket-ball** [comment]
要不然你辛苦下，加个超时自动重新运行，这样我就不用天天盯着了(

**Comment by laradocs** [comment]
> 要不然你辛苦下，加个超时自动重新运行，这样我就不用天天盯着了(

https://github.com/laradocs/moguding-solution/issues/5 能加的话我早就加了:joy:我当时也是被这个烦死，经常需要手动点一点

**Comment by basket-ball** [comment]
> > 要不然你辛苦下，加个超时自动重新运行，这样我就不用天天盯着了(
> 
> #5 能加的话我早就加了😂我当时也是被这个烦死，经常需要手动点一点

好的，还有就是我第一个问题，为啥本地运行会报错

**Comment by laradocs** [comment]
检查一下是不是 Token 填错了，我这边没遇到过这个问题

**Comment by basket-ball** [comment]
可以了，是server酱sendkey，和pushdeer搞混了，感谢 (
