### ISSUE TITLE
这种怎么办

### ISSUE THREAD

**Issue by felisrac** [laradocs/moguding-solution#27]
无法通过 https、ssh 协议克隆 https://github.com/laradocs/php-moguding-sdk.git，中止。

- https://github.com/laradocs/php-moguding-sdk.git 克隆到裸仓库 '/home/runner/.cache/composer/vcs/https---github.com-laradocs-php-moguding-sdk.git'...
 remote：已于 2021 年 8 月 13 日移除对密码身份验证的支持。
 remote：有关当前推荐的身份验证模式的信息，请参阅 https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls。
 fatal：“https://github.com/laradocs/php-moguding-sdk.git/”身份验证失败

- git@github.com：laradocs/php-moguding-sdk.git
 克隆到裸仓库“/home/runner/.cache/composer/vcs/https---github.com-laradocs-php-moguding-sdk.git”...
 git@github.com：权限被拒绝（公钥）。
 fatal：无法从远程存储库读取。
 
请确保您拥有正确的访问权限
 并且存储库存在。

**Comment by 1234-star** [comment]
那个库没得了，自己换个库改配置文件
