### ISSUE TITLE
打卡超时不会执行新的 workflow 任务

### ISSUE THREAD

**Issue by laradocs** [laradocs/moguding-solution#5]
more about: [PR#7](https://github.com/laradocs/moguding-solution/pull/7/commits/4bbdae0c55210cf3a4d19b90cea8b7141c004c7b) failed.

**Comment by EITSxiaozhai** [comment]
臣附议

**Comment by laradocs** [comment]
@EITSxiaozhai 大佬研究怎么样了？

**Comment by EITSxiaozhai** [comment]
我纯纯白嫖党的

**Comment by laradocs** [comment]
> 我纯纯白嫖党的

卧槽，我还以为你一直在研究.....难怪一直没等来 PR:joy:
